In [4]:
import pandas as pd
ufo=pd.read_csv(r'C:\Users\sarvesh\Desktop\coding week\task2.csv')
ufo

ID Segment type Segment Description Answer        Count  \
0     292890.8970          web     Meridian, Idaho     No     0.000000   
1     292887.9870          web     Meridian, Idaho     No     0.000000   
2     292894.0656       gender     Meridian, Idaho     No   499.173606   
3     292887.1180          web     Meridian, Idaho     No     0.000000   
4     292893.6561       gender     Meridian, Idaho     No   455.925963   
...           ...          ...                 ...    ...          ...   
1891  292887.5496          web     Meridian, Idaho     No     0.000000   
1892  292881.6932       mobile     Meridian, Idaho     No  1203.190399   
1893  292900.8499       gender     Meridian, Idaho     No   806.378820   
1894  292893.8600       gender     Meridian, Idaho     No  1149.529381   
1895  292890.2944          web     Meridian, Idaho     No     0.000000   

      Percentage  It became a relationship  
0       0.000000                         0  
1       0.000000                         0  
2       0.225255                         0  
3       0.000000                         0  
4       0.211360                         0  
...          ...                       ...  
1891    0.000000                         0  
1892    0.312360                         0  
1893    0.488025                         0  
1894    0.488984                         0  
1895    0.000000                         0  

[1896 rows x 7 columns]

In [5]:
ufo.isnull().sum()

ID                          0
Segment type                0
Segment Description         0
Answer                      0
Count                       0
Percentage                  0
It became a relationship    0
dtype: int64

In [119]:
X=ufo.iloc[:,4].values.reshape(-1,1)
y=ufo.iloc[:,6].values.reshape(-1,1)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [120]:

from sklearn.linear_model import LogisticRegression
clf=LogisticRegression().fit(X_train,y_train)

C:\Users\sarvesh\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [121]:
clf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [122]:
clf.score(X_test,y_test)

0.6289473684210526

In [123]:
clf.score(X_train,y_train)

0.5923482849604221

In [124]:
from sklearn.ensemble import RandomForestRegressor
fc = RandomForestRegressor().fit(X_train, y_train)
fc.predict(X_test)

<ipython-input-124-5258623bd8c9>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  fc = RandomForestRegressor().fit(X_train, y_train)


array([0.84      , 0.37099743, 0.        , 0.        , 0.        ,
       0.09174164, 0.        , 0.37099743, 1.        , 1.        ,
       0.61      , 1.        , 0.09174164, 0.37099743, 0.24      ,
       0.03      , 0.99      , 0.        , 0.        , 0.        ,
       0.7       , 1.        , 0.09174164, 0.09174164, 0.        ,
       0.        , 0.        , 0.99      , 0.        , 0.        ,
       0.97      , 1.        , 0.        , 0.        , 0.09174164,
       1.        , 0.09174164, 0.        , 0.        , 0.        ,
       0.09174164, 0.        , 0.30259524, 0.        , 0.37099743,
       0.31824511, 0.        , 0.09174164, 0.28680131, 0.05      ,
       0.        , 0.        , 0.        , 0.09174164, 0.37099743,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.09174164, 0.        , 0.9       , 0.63      , 0.57099278,
       0.14      , 0.09174164, 0.31      , 0.09174164, 1.        ,
       0.69      , 0.95      , 0.96147619, 0.09174164, 0.91   

In [125]:
fc.score(X_train,y_train)

0.7541623863640791

In [126]:
fc.score(X_test,y_test)

0.4111307090432662

In [127]:
from sklearn.ensemble import GradientBoostingRegressor
lc= GradientBoostingRegressor().fit(X_train, y_train)
lc.score(X_train,y_train)

C:\Users\sarvesh\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.6616585525516043

In [128]:
lc.score(X_test,y_test)

0.4762749823901441

In [129]:
lc.predict(X_test)

array([0.5927925 , 0.38655224, 0.01438463, 0.01438463, 0.01438463,
       0.0942987 , 0.00821299, 0.38655224, 0.90034373, 0.90509381,
       0.2218215 , 0.89434935, 0.0942987 , 0.38655224, 0.79758622,
       0.37827279, 0.92389042, 0.01438463, 0.0233844 , 0.0233844 ,
       0.6067778 , 0.98135639, 0.0942987 , 0.0942987 , 0.01438463,
       0.00821299, 0.01438463, 0.862022  , 0.01438463, 0.01438463,
       0.85335431, 0.73804298, 0.00821299, 0.01438463, 0.0942987 ,
       0.98135639, 0.0942987 , 0.00821299, 0.00821299, 0.00821299,
       0.0942987 , 0.00821299, 0.52805107, 0.00821299, 0.38655224,
       0.37091153, 0.00821299, 0.0942987 , 0.52805107, 0.00821299,
       0.00821299, 0.01438463, 0.0233844 , 0.0942987 , 0.38655224,
       0.01438463, 0.79158679, 0.00821299, 0.01438463, 0.01438463,
       0.0942987 , 0.01438463, 0.89434935, 0.87129587, 0.6375257 ,
       0.52805107, 0.0942987 , 0.6067778 , 0.0942987 , 0.98135639,
       0.77080645, 0.90024799, 0.536891  , 0.0942987 , 0.84117